### ISSUE TITLE
Relation Types Export Exception being thrown

### ISSUE THREAD

**Issue by JcRichards1991** [KevinJump/uSync8#190]
**Describe the bug**
Exception thrown when export Relation Types using uSync v8.7.2  + ContentEdition v8.7.22

**To Reproduce**
1. Saving of a Relation Type / Full (/clean) uSync export causes exception to be thrown

**Expected behavior**
Relation Types to be exported  to disk on save/full (/clean) export

**Desktop (please complete the following information):**
 - Umbraco Version: 8.9.1
 - uSync Version: 8.7.2 + ContentEdition v8.7.22
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
Exception in logs:

`System.MissingMethodException: Method not found: System.Guid Umbraco.Core.Models.IRelationType.get_ParentObjectType().
   at uSync8.ContentEdition.Serializers.RelationTypeSerializer.SerializeCore(IRelationType item, SyncSerializerOptions options)
   at uSync8.BackOffice.SyncHandlers.SyncHandlerRoot2.Export(TObject item, String folder, HandlerSettings config)
   at uSync8.BackOffice.SyncHandlers.SyncHandlerRoot2.EventSavedItem(IService sender, SaveEventArgs1 e)
   at Umbraco.Core.Events.TypedEventHandler2.Invoke(TSender sender, TEventArgs e)
   at Umbraco.Core.Events.EventDefinition2.RaiseEvent() in D:\a\1\s\src\Umbraco.Core\Events\EventDefinition.cs:line 71
   at Umbraco.Core.Events.QueuingEventDispatcher.ScopeExitCompleted() in D:\a\1\s\src\Umbraco.Core\Events\QueuingEventDispatcher.cs:line 29
   at Umbraco.Core.Events.QueuingEventDispatcherBase.ScopeExit(Boolean completed) in D:\a\1\s\src\Umbraco.Core\Events\QueuingEventDispatcherBase.cs:line 338
   at Umbraco.Core.Scoping.Scope.<>c__DisplayClass71_0.<RobustExit>b__1() in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 434
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 472
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 477
   at Umbraco.Core.Scoping.Scope.RobustExit(Boolean completed, Boolean onException) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 460
   at Umbraco.Core.Scoping.Scope.Dispose() in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 365
   at Umbraco.Core.Services.Implement.RelationService.Save(IRelationType relationType) in D:\a\1\s\src\Umbraco.Core\Services\Implement\RelationService.cs:line 485
   at Umbraco.Web.Editors.RelationTypeController.PostSave(RelationTypeSave relationType) in D:\a\1\s\src\Umbraco.Web\Editors\RelationTypeController.cs:line 172`

**Comment by KevinJump** [comment]
Hi,

What type of relation type is it you are trying to export (e.g document -> document, member -> member) - I suspect there is an internal umbraco thing we need to catch ,

We don't actually call any of the offending methods i think this happens when the item is loaded in and not all item types can be transferred to an ObjectType inside umbraco - but we might be able to track that down.

**Comment by JcRichards1991** [comment]
Hi @KevinJump

Below screen grab are the Relation Types we have configured. The "Relate Tour to Hotel" is the only custom one we have added. I believe the others are OOTB with umbraco

![image](https://user-images.githubusercontent.com/17648147/102209502-c128f400-3ec8-11eb-815d-659ce1441483.png)

Cheers,
Joshua

**Comment by KevinJump** [comment]
thanks, what type of relationship is relate Tour to Hotels ? 
e.g the parent and child ? 

![image](https://user-images.githubusercontent.com/431231/102209729-1bc25000-3ec9-11eb-9020-3b38dd32b9e3.png)

**Comment by KevinJump** [comment]
Don't worry i think i've found it, the new Relate Media and Relate document doc types (added in i think umbraco v8.8) don't havea parent or child - and that breaks the internal buisness logic in umbraco (i think!). 

We will work around it.

**Comment by JcRichards1991** [comment]
Hi @KevinJump 

That's annoying, but good to hear.

Regards,
Joshua

**Comment by KevinJump** [comment]
fixed in v8.8.0
