### ISSUE TITLE
System.NullReferenceException while exporting DocTypes using v8.8.0

### ISSUE THREAD

**Issue by creativesuspects** [KevinJump/uSync8#193]
**Describe the bug**
I'm getting a System.NullReferenceException when generating an export using uSync v8.8.0. I've tested it on two separate projects and in both cases the error occurs when exporting DocTypes. The export process freezes once the error occurs.

**To Reproduce**
1. Go to 'Settings' dashboard
2. Click on 'uSync'
3. Click on 'Export'
4. See error while exporting DocTypes

**Desktop (please complete the following information):**
 - Umbraco Version: 8.9.1
 - uSync Version: 8.8.0
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at uSync8.BackOffice.SyncHandlers.SyncHandlerTreeBase`2.GetItemName(TObject item)
   at uSync8.BackOffice.SyncHandlers.SyncHandlerRoot`2.ExportAll(TContainer parent, String folder, HandlerSettings config, SyncUpdateCallback callback)
   at uSync8.BackOffice.SyncHandlers.SyncHandlerRoot`2.ExportAll(TContainer parent, String folder, HandlerSettings config, SyncUpdateCallback callback)
   at uSync8.BackOffice.SyncHandlers.SyncHandlerRoot`2.ExportAll(String folder, HandlerSettings config, SyncUpdateCallback callback)
   at uSync8.BackOffice.uSyncService.Export(String folder, IEnumerable`1 handlers, uSyncCallbacks callbacks)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
```

RequestUrl: /umbraco/backoffice/uSync/uSyncDashboardApi/export
SourceContext: uSync8.BackOffice.Controllers.uSyncDashboardApiController

I've attached Umbraco exports (.udt) of the document types. Maybe that helps to investigate. I noticed both doctypes don't have any 'Allowed Templates' configured. Maybe that has something to do with it.

[appConfig.txt](https://github.com/KevinJump/uSync8/files/5702977/appConfig.txt)
[mailTemplate.txt](https://github.com/KevinJump/uSync8/files/5702978/mailTemplate.txt)

**Comment by creativesuspects** [comment]
I've also attached the exports for those same doctypes that were created using uSync 8.7.2. Everything worked fine in that version.

[appconfig.config.txt](https://github.com/KevinJump/uSync8/files/5703028/appconfig.config.txt)
[mailtemplate.config.txt](https://github.com/KevinJump/uSync8/files/5703027/mailtemplate.config.txt)

**Comment by KevinJump** [comment]
😢 -thanks  we'll take a look

**Comment by creativesuspects** [comment]
If you need any input from my end I can jump on Skype or whatever. Good luck!

**Comment by KevinJump** [comment]
thanks, i think i know what i've done. its probably the allowed template bit

**Comment by creativesuspects** [comment]
Do you have any idea when you'll be releasing a fix? No rush, but if it's going to take a while I'll just do a rollback to v8.7.2.

**Comment by KevinJump** [comment]
Hi, 

Just doing the checks now, i think we have it, but i need to confirm . about 1 hour .

**Comment by creativesuspects** [comment]
Awesome! In that case I'll just wait for the new release.

**Comment by KevinJump** [comment]
Done: 
https://www.nuget.org/packages/uSync/8.8.1

PM> Install-Package uSync -Version 8.8.1

**Comment by creativesuspects** [comment]
Updated and works like a charm!

**Comment by KevinJump** [comment]
phew 👍
