### ISSUE TITLE
Boot failed execption when trying to execute usync.exe init

### ISSUE THREAD

**Issue by SKA91** [KevinJump/uSync8#217]
Hi,

I've installed the uSync.Console package and want to try out the CLI functionality.

When I run the init argument on my local machine I get the following boot exception:

```
{"@t":"2021-04-12T10:06:37.0673333Z","@mt":"{FailMessage} ({Duration}ms) [Timing {TimingId}]","@l":"Error","@x":"Umbraco.Core.Exceptions.BootFailedException: Boot failed. ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.Web.Hosting.HostingEnvironment.RegisterVirtualPathProvider(VirtualPathProvider virtualPathProvider)
   at Our.Umbraco.FileSystemProviders.Azure.FileSystemVirtualPathProvider.Configure(String pathPrefix)
   at Our.Umbraco.FileSystemProviders.Azure.AzureMediaFileSystemComponent.Initialize()
   at Umbraco.Core.Composing.ComponentCollection.Initialize()
   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer)
   --- End of inner exception stack trace ---","FailMessage":"Boot failed.","Duration":5592,"TimingId":"fc09a03","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":29724,"ProcessName":"uSync","ThreadId":1,"AppDomainId":2,"AppDomainAppId":"FromDomain","MachineName":"","Log4NetLevel":"ERROR"}
```
```
<PackageReference Include="uSync.Console" Version="8.9.0-rc" />
<PackageReference Include="uSync.Core" Version="8.8.3" />
<PackageReference Include="UmbracoCms.Core" Version="8.11.1" />
```

It might not be compatible with the Azure FileSystemProviders yet?

**Comment by KevinJump** [comment]
yeah - not sure will have a check.

**Comment by KevinJump** [comment]
Hi,

We are just cleaning up old, issues, i hope this was something that has either been fixed for you or not happened again. 
if this is still an issue, then feel free to drop in a comment and we will look at re-opening the issue. 

♾️
