### ISSUE TITLE
Issue Pushing from one environment to another

### ISSUE THREAD

**Issue by JohnBergman** [KevinJump/uSync8#242]
v8.9.0.0 + Content Edition (v8.9.0.0), Snapshots (v8.9.3.0), Exporter (v8.9.3.0), PeopleEdition (v8.9.3.1), Publisher (v8.9.3.0), Complete (v8.9.3.0), FormsEdition (v8.0.0.0)

Umbraco 8.12.2
using a chrome browser (latest version)

We started a push, and after a little while the UI hung up here

![image](https://user-images.githubusercontent.com/5505858/120385470-162cbb00-c2ed-11eb-82f3-9eb2add166b2.png)

Looking in the logs these stood out

![image](https://user-images.githubusercontent.com/5505858/120385572-33fa2000-c2ed-11eb-8536-d5b5b3009e2a.png)

Here is the stack trace

```
    
System.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.umbracoRelation' with unique index 'IX_umbracoRelation_parentChildType'. The duplicate key value is (7580, 7655, 2). The statement has been terminated. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() at System.Data.SqlClient.SqlDataReader.get_MetaData() at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) at System.Data.SqlClient.SqlCommand.ExecuteScalar() at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172 at NPoco.Database.ExecuteScalarHelper(DbCommand cmd) at NPoco.Database.InsertImp[T](PocoData pocoData, String tableName, String primaryKeyName, Boolean autoIncrement, T poco) ClientConnectionId:96b3d2ed-ae82-4d5a-8053-3407c3f4e85b Error Number:2601,State:1,Class:14
"publishedContentHandler": Import Failed : "System.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.umbracoRelation' with unique index 'IX_umbracoRelation_parentChildType'. The duplicate key value is (7580, 7655,
 2). The statement has been terminated. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean
 callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at
 System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() at System.Data.SqlClient.SqlDataReader.get_MetaData() at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal,
 Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean
 asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1
 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) at System.Data.SqlClient.SqlCommand.ExecuteScalar()
 at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172 at NPoco.Database.ExecuteScalarHelper(DbCommand cmd) at NPoco.Database.InsertImp[T](PocoData
 pocoData, String tableName, String primaryKeyName, Boolean autoIncrement, T poco) at NPoco.Database.Insert[T](String tableName, String primaryKeyName, Boolean autoIncrement, T poco) at NPoco.Database.Insert[T](T poco) at Umbraco.Core.Persistence.Repositories.Implement.RelationRepository.PersistNewItem(IRelation
 entity) in D:\a\1\s\src\Umbraco.Core\Persistence\Repositories\Implement\RelationRepository.cs:line 139 at Umbraco.Core.Services.Implement.RelationService.Save(IRelation relation) in D:\a\1\s\src\Umbraco.Core\Services\Implement\RelationService.cs:line 444 at
 Umbraco.Core.Compose.RelateOnTrashComponent.ContentService_Trashed(IContentService sender, MoveEventArgs`1 e) in D:\a\1\s\src\Umbraco.Core\Compose\RelateOnTrashComponent.cs:line 89 at Umbraco.Core.Events.TypedEventHandler`2.Invoke(TSender sender, TEventArgs
 e) at Umbraco.Core.Events.EventDefinition`2.RaiseEvent() in D:\a\1\s\src\Umbraco.Core\Events\EventDefinition.cs:line 71 at Umbraco.Core.Events.QueuingEventDispatcher.ScopeExitCompleted() in D:\a\1\s\src\Umbraco.Core\Events\QueuingEventDispatcher.cs:line 29
 at Umbraco.Core.Events.QueuingEventDispatcherBase.ScopeExit(Boolean completed) in D:\a\1\s\src\Umbraco.Core\Events\QueuingEventDispatcherBase.cs:line 338 at Umbraco.Core.Scoping.Scope.<>c__DisplayClass71_0.<RobustExit>b__1() in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line
 435 at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 473 at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 478
 at Umbraco.Core.Scoping.Scope.RobustExit(Boolean completed, Boolean onException) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 461 at Umbraco.Core.Scoping.Scope.Dispose() in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 366 at Umbraco.Core.Services.Implement.ContentService.MoveToRecycleBin(IContent
 content, Int32 userId) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1933 at uSync.Expansions.PublishedContent.PublishedContentHandler.DeleteViaService(IContent item) at uSync8.BackOffice.SyncHandlers.SyncHandlerBase`2.DeleteMissingItems(TObject
 parent, IEnumerable`1 keys, Boolean reportOnly) at uSync8.BackOffice.SyncHandlers.SyncHandlerRoot`2.ImportElement(XElement node, String filename, HandlerSettings settings, uSyncImportOptions options) ClientConnectionId:96b3d2ed-ae82-4d5a-8053-3407c3f4e85b
 Error Number:2601,State:1,Class:14"
```

We also noticed this while we were looking at the site we pushed to

![image](https://user-images.githubusercontent.com/5505858/120385755-715ead80-c2ed-11eb-9ef1-1161c6ab48b3.png)

![image](https://user-images.githubusercontent.com/5505858/120385817-80ddf680-c2ed-11eb-8d05-0ca58c621427.png)

While we don't think it is the case, perhaps there were 2 sync jobs executed?  Not really sure why we could get the duplicate key issue otherwise, since the content is only editted in the environment we pushed from.

**Comment by JohnBergman** [comment]
Trying the Sync again, we received this error:
![image](https://user-images.githubusercontent.com/5505858/120389992-c5b85c00-c2f2-11eb-9865-53315560354d.png)

The settings inside the portal of both are set like this:
![image](https://user-images.githubusercontent.com/5505858/120390056-dbc61c80-c2f2-11eb-8493-cf78e8ff0a3a.png)

and
![image](https://user-images.githubusercontent.com/5505858/120390097-e97ba200-c2f2-11eb-88fd-a6ad0314d3bb.png)

**Comment by KevinJump** [comment]
Hi,

I think the first issue is coming up when Umbraco is adding a releationship for a deleted item 

Umbraco adds a relationship so it knows how to restore an item when its moved to the recycle bin. When an item is deleted uSync will put it in the bin, so that s the point its happening - i would say you can't delete something twice but it does look like that is what is happening, we might be able to wrap this, but will want to do a couple of tests to see if we can replicate it happening.


second issue - is either load balancing or long file names. - the flat setting relates to how uSync handles its internal files but not media files (which keep their name) so media items with long file names in paths do appear to get very long. - we are going to look at this maybe hashing the filenames in the sync pack - although this won't solve issues if the file name is then to long to go into the source location). https://github.com/Jumoo/uSync.Complete.Issues/issues/115 - This is something we doing for the next release.

**Comment by KevinJump** [comment]
Hi, 

We have released a new version of uSync.Complete today that should help with this issue. 
(see https://github.com/Jumoo/uSync.Complete.Issues/releases/tag/8.10.0)

this includes a new SafeMediaName setting, that when set- will rename media files in the temp folder (it gives them a `{guid}.extension` pattern) - the files are renamed back when imported at the other end, so in theory this gets around the long file names issue. 

for v8.10 you need to add the following to the uSync8.config (and restart the site) - to activate this. (and both ends of the process need to be running uSync.Complete v8.10)

```
<Complete>
   <SafeMediaNames>True</SafeMediaNames>
</Complete>
```

(docs: https://docs.jumoo.co.uk/uSync/uSync.Complete/config/longfilenames/)
