### ISSUE TITLE
Unable to access _dependencies.config

### ISSUE THREAD

**Issue by marklonquist** [KevinJump/uSync8#320]
![image](https://user-images.githubusercontent.com/1456819/145798792-e0f34ee8-dfce-4396-83ea-e71cdc9f4033.png)

```
Access to the path '/_dependencies.config' is denied.
    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at uSync.Expansions.Core.Physical.SyncPackFileService.SafeUnzip(String zipfile, String target)
   at uSync.Expansions.Core.Physical.SyncPackFileService.UnpackStream(String file, Stream stream)
   at uSync.Publisher.Services.SyncPublishService.UnpackStream(Guid id, Stream stream)
   at uSync.Publisher.Publishers.SyncRealtimePublisher.PullFromRemote(PublisherActionRequest request, String method)
   at uSync.Publisher.Publishers.SyncRealtimePublisher.PullFromRemote(PublisherActionRequest request, String method)
   at uSync.Publisher.Publishers.SyncRealtimePublisher.PullSingleFile(PublisherActionRequest request, String method)
   at uSync.Publisher.Publishers.SyncRealtimePublisher.PullFetch(PublisherActionRequest request)
   at uSync.Publisher.Controllers.uSyncPublisherApiController.PerformAction(PublisherActionRequest request)
```

While trying to push or pull content, we get the above error. Our umbraco 9 instances are running on alpine linux (so.. Linux) using containers.

It's wierd though, because it seems the file has been created - even with the correct user. And it is readable.

**Comment by KevinJump** [comment]
thanks, i will take a look i suspect its a containers thing, will see if i can spin something up and replicate. if you could confirm the casing is OK for the file/path (we do test on case sensitive folders, but its always worth a check).

**Comment by marklonquist** [comment]
Is the path even correct to the file? Seems like it's looking for it at the root.

Shouldn't it be looking at ~/umbraco/Data/TEMP/uSync/X/XXXX?

**Comment by KevinJump** [comment]
Hi yeah i think one of two things is happening, 

either 
a) for some reason the target folder is getting lost when we are calculating the location to unzip to. Now this is generated from the request ID (a guid) and the temp folder (an umbraco/asp.net setting) - hopefully that is quite robust, but if it was blank it might exhibit this behavior _(although is the guid was blank i would expect 0000-0000.....)_

b) the way the file is zipped is slightly different on Linux and we have a leading `/` or similar in the zip path somewhere. 

We have done an update - to check this which will
1) throw an exception if the target folder reached the unzip folder blank
2) removes and leading / or \ values from the item name in the zip


if you are able it would be a great help if you could try our latest nightly beta build (details below) 

hopefully this will either fix this issue or highlight to us better where things are going wrong. 🤞

https://dev.azure.com/jumoo/Public/_packaging?_a=package&feed=nightly&package=uSync.Complete&protocolType=NuGet&version=9.0.5-beta001.20211213.1

**Comment by marklonquist** [comment]
I'll update to the nightly tomorrow morning and get back to you. 🙃

**Comment by marklonquist** [comment]
with the nightly we were able to push data between environments.

However, after a push data is not always updated correctly. We push a page that has all blocks in a block list removed, but they are still present on the destination.

Is block lists not being handled yet?

**Comment by KevinJump** [comment]
Hi 

the block lists should work -  Are you using any variant language stuff (how partial languages are synced can effect this?) - 

but we will take a look at that.

**Comment by marklonquist** [comment]
We're using the built-in language system. Nothing third-party. :-)

**Comment by KevinJump** [comment]
Hi Just to confirm removing blocks (some or all) froma block list property does work when testing.

Just to confirm uSync.Publisher syncs **published** content between servers (so if you remove the block elements and only save content - then when you push to the other server they will still be there as they are still published on the source).

if its not this It might be a Linux thing that will take a little more investigation - we will have to get some linux tests spun up to confirm what we can see - if it was a linux thing i would suspect a lot of other things would also be noticeable as it would likely be around how the sync worked, not just one or two properties - but we will take a look, it might just take a little longer.

**Comment by KevinJump** [comment]
Hi,

We are just cleaning up old, issues, i hope this was something that has either been fixed for you or not happened again. 
if this is still an issue, then feel free to drop in a comment and we will look at re-opening the issue. 

♾️
