### ISSUE TITLE
Problems with backoffice language at publish

### ISSUE THREAD

**Issue by Sophiehillebrant** [KevinJump/uSync8#337]
**Describe the bug**
When the editors backoffice language is set to Swedish (so far I have identified the problem occurring for svenska(Sverige) and norskt bokmål(Norge) ), I am not able to publish any pages. An error is thrown (see screenshot). The other languages seem to work perfectly fine, no error and the page published as expected. Maybe it is expected behavior and usync for Umbraco 9 does not support Swedish and Norwegian as backoffice languages?

**To Reproduce**
1. Change the backoffice language for editor to Swedish.
2. Try to publish a page in the content tree.
3. See error.

**Expected behavior**
When publishing a page, I should not get this error and the page should be published

**Screenshots**
![image](https://user-images.githubusercontent.com/55388568/152133268-6c7e7224-97e4-4446-8d6f-e3dc58ce8f24.png)

**About your Site (please complete the following information):**
 - Umbraco Version: 9.2.0
 - uSync Version: 9.0.6
 - Browser [e.g. chrome, safari]: Chrome

**Additional context**
Full stack trace in error message:

Input string was not in a correct format.

Exception Details:
System.FormatException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Input string was not in a correct format.

at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at uSync.Core.Serialization.Serializers.ContentSerializerBase`1.<>c.<GetFriendlyPath>b__33_0(String x)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at uSync.Core.Serialization.Serializers.ContentSerializerBase`1.GetFriendlyPath(String path)
   at uSync.Core.Serialization.Serializers.ContentSerializerBase`1.GetItemPath(TObject item)
   at uSync.Core.Serialization.Serializers.ContentSerializerBase`1.SerializeInfo(TObject item, SyncSerializerOptions options)
   at uSync.Core.Serialization.Serializers.ContentSerializer.SerializeInfo(IContent item, SyncSerializerOptions options)
   at uSync.Core.Serialization.Serializers.ContentSerializer.SerializeCore(IContent item, SyncSerializerOptions options)
   at uSync.Core.Serialization.SyncSerializerRoot`1.Serialize(TObject item, SyncSerializerOptions options)
   at uSync.BackOffice.SyncHandlers.SyncHandlerRoot`2.SerializeItem(TObject item, SyncSerializerOptions options)
   at uSync.BackOffice.SyncHandlers.SyncHandlerRoot`2.Export(TObject item, String folder, HandlerSettings config)
   at uSync.BackOffice.SyncHandlers.SyncHandlerRoot`2.Handle(SavedNotification`1 notification)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore(IEnumerable`1 allHandlers, INotification notification)
   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification](TNotification notification)
   at Umbraco.Cms.Core.Events.ScopedNotificationPublisher.ScopeExit(Boolean completed)
   at Umbraco.Cms.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Cms.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions)
   at Umbraco.Cms.Core.Scoping.Scope.Dispose()
   at Umbraco.Cms.Core.Services.Implement.ContentService.SaveAndPublish(IContent content, String[] cultures, Int32 userId)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PublishInternal(ContentItemSave contentItem, String defaultCulture, String cultureForInvariantErrors, Boolean& wasCancelled, String[]& successfulCultures)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSaveInternal(ContentItemSave contentItem, Func`2 saveMethod, Func`2 mapToDisplay)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSave(ContentItemSave contentItem)
   at lambda_method1397(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by KevinJump** [comment]
Thanks, 

Interesting. i think its this https://github.com/dotnet/runtime/issues/40922 
which is essentially some languages don't like -1 because - isn't minus - every day is a day at school. 

we can fix this. for next release,

**Comment by Sophiehillebrant** [comment]
Oh yeah, tricky one to spot! Sounds great, much appreciated :)
