### ISSUE TITLE
v10-rc1 current version (v9.4.0) causes a boot failure.

### ISSUE THREAD

**Issue by jamiepollock** [KevinJump/uSync8#390]
**Describe the bug**

**To Reproduce**
1. Create a fresh copy of Umbraco 10 RC1
2. Install uSync latest
3. Build & run website

**Expected behavior**
uSync should not crash app boot.

**Screenshots**
![Screenshot 2022-05-13 122248](https://user-images.githubusercontent.com/5408006/168326241-88048fd8-bcb2-44b8-9bb3-48ce9e7fd6c9.png)

**About your Site (please complete the following information):**
 - Umbraco Version: Umbraco 10 RC1
 - uSync Version: 9.4.0
 - Browser Chrome

**Additional context**
To be fair, this is a realistic bugfix for v9.4.0 and was included more as a note that there are breaking changes in v10 RC1 which uSync will need to account for when v10 compatible version comes out.

Here is the detailed callstack too.

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Umbraco.Cms.Infrastructure.Migrations.ExecutedMigrationPlan Umbraco.Cms.Infrastructure.Migrations.Upgrade.Upgrader.Execute(Umbraco.Cms.Core.Migrations.IMigrationPlanExecutor, Umbraco.Cms.Core.Scoping.IScopeProvider, Umbraco.Cms.Core.Services.IKeyValueService)'.
  Source=uSync.BackOffice
  StackTrace:
   at uSync.BackOffice.Boot.FirstBootAppStartingHandler.Handle(UmbracoApplicationStartingNotification notification)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.<>c__DisplayClass0_0.<Handle>b__1(INotification theNotification)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore(IEnumerable`1 allHandlers, INotification notification)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle(INotification notification, ServiceFactory serviceFactory, Action`2 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotification(INotification notification)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishAsync[TNotification](TNotification notification, CancellationToken cancellationToken)
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.<StartAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.<StartAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at MyUmbracoWebsite.Program.Main(String[] args) in C:\Path\To\My\Website\Program.cs:line 13

  This exception was originally thrown at this call stack:
    [External Code]
    MyUmbracoWebsite.Program.Main(string[]) in Program.cs
```

**Comment by jamiepollock** [comment]
Looks like v9.3.2 works fine because it doesn't have FirstBoot.

**Comment by jamiepollock** [comment]
I've tried disabling FirstBootOnImport but [the migration will still run](https://github.com/KevinJump/uSync/blob/26c6cf1ecafa7cc6e7d4fdc4a51883abc61e7673/uSync.BackOffice/Boot/uSyncBootExtension.cs#L67-L81) and that's the conflict we're seeing with v10 RC1.

**Comment by KevinJump** [comment]
Yes there is a breaking change with the scope (its moved to ICoreScope - i[ think the intention was for this not to be a breaking change in v10](https://github.com/umbraco/Umbraco-CMS/discussions/12217#discussioncomment-2502252) - but it looks like it is 

Anyway - uSync 10.0 beta1 is out now, and all this works. 🎉 

https://www.nuget.org/packages/uSync/10.0.0-beta1

**Comment by jamiepollock** [comment]
@KevinJump great work. Thanks Kevin.
