### ISSUE TITLE
Execution Timeout Expired when importing content type changes

### ISSUE THREAD

**Issue by AlexandreLocas** [KevinJump/uSync8#57]
Hi, when trying to import settings we receive the following error (see bottom).

- uSync v8.2.1.924 + Content Edition.
- The database used is a Azure SQL database. 
- The update is to add 5 properties to a content type. 
- There are about 800 nodes usings this document type.

I changed the 'Connection timeout' property on connection string but it had no effect. It seems to rather be SQL's CommandTimeout that should be increased.

Thank you

`System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in d:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)
   at NPoco.Database.ExecuteScalar[T](String sql, CommandType commandType, Object[] args)
ClientConnectionId:809b4e9e-1d0d-49ff-8ac3-0386f4539795
Error Number:-2,State:0,Class:11
ClientConnectionId before routing:fbc7fa39-f3d6-4b4e-8d32-f9b15aa7cf82
Routing Destination:e0688902d0bd.tr3.canadacentral1-a.worker.database.windows.net,11133`

**Comment by AlexandreLocas** [comment]
Thanks for the quick answer, I'll try it directly with Umbraco to confirm this.

**Comment by AlexandreLocas** [comment]
I confirm that adding a property directly with Umbraco also produces the error. I will add an Issue there.
