### ISSUE TITLE
Missing File Error when deleting content .

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync8#66]
As reported here : https://our.umbraco.com/packages/developer-tools/usync/usync/99956-encountered-a-missing-file-error-when-deleting-a-node#comment-314175

```
System.IO.FileNotFoundException: Missing File
File name: 'D:\home\site\wwwroot\uSync\v8\Content\bf593ab2-1227-4140-95da-a2b3b50033cc.config'
   at uSync8.BackOffice.Services.SyncFileService.EnsureFileExists(String path)
   at uSync8.BackOffice.Services.SyncFileService.LoadXElement(String file)
   at uSync8.BackOffice.SyncHandlers.SyncHandlerBase`2.CleanUp(TObject item, String newFile, String folder)
   at uSync8.BackOffice.SyncHandlers.SyncHandlerBase`2.EventMovedItem(IService sender, MoveEventArgs`1 e)
   at Umbraco.Core.Events.TypedEventHandler`2.Invoke(TSender sender, TEventArgs e)
   at Umbraco.Core.Events.EventDefinition`2.RaiseEvent() in D:\a\1\s\src\Umbraco.Core\Events\EventDefinition.cs:line 69
   at Umbraco.Core.Events.QueuingEventDispatcher.ScopeExitCompleted() in D:\a\1\s\src\Umbraco.Core\Events\QueuingEventDispatcher.cs:line 23
   at Umbraco.Core.Events.QueuingEventDispatcherBase.ScopeExit(Boolean completed) in D:\a\1\s\src\Umbraco.Core\Events\QueuingEventDispatcherBase.cs:line 337
   at Umbraco.Core.Scoping.Scope.<>c__DisplayClass72_0.<RobustExit>b__1() in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 436
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 474
   at Umbraco.Core.Scoping.Scope.TryFinally(Int32 index, Action[] actions) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 478
   at Umbraco.Core.Scoping.Scope.RobustExit(Boolean completed, Boolean onException) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 422
   at Umbraco.Core.Scoping.Scope.DisposeLastScope() in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 402
   at Umbraco.Core.Scoping.Scope.Dispose() in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 365
   at Umbraco.Core.Services.Implement.ContentService.MoveToRecycleBin(IContent content, Int32 userId) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 1905
   at Umbraco.Web.Editors.ContentController.DeleteById(Int32 id)
```

Might be a corruption, file permissions or a concurrency issue

**Comment by KevinJump** [comment]
fixed.
